[package]
name = "mic_to_text"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.83"
async-openai = "0.21.0"
cpal = "0.15.3"
hound = "3.5.1"
tokio = { version = "1.37.0", features = ["full"] }
